name: Backend CI

on:
  push:
    branches:
      - main
      - 'be/**'
      - 'all/**'
    paths:
      - 'apps/backend/**'
      - 'packages/shared/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'apps/backend/**'
      - 'packages/shared/**'
      - 'package.json'
      - 'package-lock.json'

jobs:
  lint-and-format:
    name: Lint & Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.5'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint:backend

      - name: Check formatting
        run: npm run format:backend

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.5'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test:backend

      - name: Run E2E tests
        run: npm run test:backend:e2e
        continue-on-error: true  # E2E tests might not exist yet

  build:
    name: Build Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.5'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build backend
        run: npm run build:backend

      - name: Check build output
        run: |
          if [ ! -d "apps/backend/dist" ]; then
            echo "Build failed: dist directory not found"
            exit 1
          fi
          echo "✅ Build successful"